services:
  go-service:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    container_name: loresmith-go-service
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: loresmith-python-service
    ports:
      - "50051:50051"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:8
    container_name: loresmith-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:12.4-alpine
    container_name: loresmith-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

volumes:
  postgres_data:
