apiVersion: apps/v1
kind: Deployment
metadata:
  name: loresmith-backend
  labels:
    app: loresmith-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loresmith-backend
  template:
    metadata:
      labels:
        app: loresmith-backend
    spec:
      containers:
        - name: backend
          image: vexenbay/loresmith-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Secrets
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: loresmith-secrets
                  key: API-KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loresmith-secrets
                  key: POSTGRES_PASSWORD

            # ConfigMap keys for non-sensitive env vars
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: REDIS_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: loresmith-config
                  key: POSTGRES_USER
