apiVersion: v1
kind: ConfigMap
metadata:
  name: loresmith-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "loresmith"
  POSTGRES_USER: "loresmith_user"
