apiVersion: apps/v1
kind: Deployment
metadata:
  name: loresmith-backend
  labels:
    app: loresmith-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loresmith-backend
  template:
    metadata:
      labels:
        app: loresmith-backend
    spec:
      containers:
        - name: backend
          image: vexenbay/loresmith-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openrouter-secret
                  key: api-key
