"""add_missing_lore_piece_columns

Revision ID: 5abf45803efc
Revises: 666c68d19c77
Create Date: 2025-08-10 18:41:39.657966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5abf45803efc"
down_revision: Union[str, Sequence[str], None] = "666c68d19c77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lore_pieces", sa.Column("name", sa.String(), nullable=False))
    op.add_column("lore_pieces", sa.Column("description", sa.String(), nullable=False))
    op.add_column("lore_pieces", sa.Column("theme", sa.String(), nullable=False))
    op.add_column("lore_pieces", sa.Column("details", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_lore_pieces_id"), "lore_pieces", ["id"], unique=False)
    op.drop_column("lore_pieces", "created_at")
    op.drop_column("lore_pieces", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lore_pieces",
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "lore_pieces",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_lore_pieces_id"), table_name="lore_pieces")
    op.drop_column("lore_pieces", "details")
    op.drop_column("lore_pieces", "theme")
    op.drop_column("lore_pieces", "description")
    op.drop_column("lore_pieces", "name")
    # ### end Alembic commands ###
