"""add hashed_password to users

Revision ID: 666c68d19c77
Revises: 9ee7f31d04c0
Create Date: 2025-07-19 13:39:40.655522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "666c68d19c77"
down_revision: Union[str, Sequence[str], None] = "9ee7f31d04c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
