"""This module defines a blacklist of words and full names that are not allowed
in generated content to ensure originality and avoid overused themes."""

BLACKLIST = {
    "words": [
        "ashen",
        "cinder",
        "thorn",
        "veil",
        "wraith",
        "covenant",
        "echo",
        "wasteland",
        "dawn",
        "silence",
        "whisper",
        "shadow",
        "scorch",
        "ember",
        "hollow",
        "blight",
        "forsaken",
        "ruin",
        "phantom",
        "iron",
        "broken",
        "dead",
        "dust",
        "scar",
        "skymaker",
        "shriek",
        "mirage",
        "frost",
        "storm",
        "elemental",
        "aurora",
        "celestial",
        "fire",
        "flame",
        "blood",
        "bone",
        "glitch",
        "circuit",
        "neon",
        "cyber",
        "synth",
        "tech",
        "byte",
        "data",
        "pixel",
        "void",
        "nexus",
        "matrix",
        "chrome",
        "steel",
        "razor",
    ],
    "full_names": [
        "ashen wraith",
        "ashen covenant",
        "wasteland echoes",
        "silence of the ashen dawn",
        "eclipse of whispers",
        "silent dawn",
        "ghost hollow",
        "scorching ember",
        "broken blade",
        "dust scar",
        "phantom flame",
    ],
}
