BLACKLIST = {
    "words": [
        "ashen",
        "thorn",
        "wraith",
        "covenant",
        "echo",
        "wasteland",
        "dawn",
        "silence",
        "whisper",
        "shadow",
        "scorch",
        "ember",
        "hollow",
        "blight",
        "forsaken",
        "ruin",
        "phantom",
        "iron",
        "broken",
        "dead",
        "dust",
        "scar",
        "fire",
        "flame",
        "blood",
        "bone",
    ],
    "full_names": [
        "ashen wraith",
        "ashen covenant",
        "wasteland echoes",
        "silence of the ashen dawn",
        "eclipse of whispers",
        "silent dawn",
        "ghost hollow",
        "scorching ember",
        "broken blade",
        "dust scar",
        "phantom flame",
    ],
}
