name: CI

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  test:
    name: CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff Linter
        run: |
          source venv/bin/activate
          ruff check .

      - name: Run Black Formatter
        run: |
          source venv/bin/activate
          black --check .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t vexenbay/loresmith-backend:latest .

      - name: Push Docker image
        run: docker push vexenbay/loresmith-backend:latest

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment/loresmith-backend
