name: CI

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff Linter
        run: |
          source venv/bin/activate
          ruff check .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/
